name: Test Grep

on: workflow_dispatch

jobs:
  testgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "grep matching pattern"
        timeout-minutes: 1
        run: |
         set -eo pipefail
         # Everything works fine
         echo "foo" | grep "foo"
         sleep 70
      - name: "grep not matching pattern"
        run: |
          set -eo pipefail
          # Workflow failes because grep exits with 1
          echo "foo" | grep "bar"
