name: Test

on: workflow_dispatch

jobs:
  job_1:
    runs-on: ubuntu-latest
    outputs:
      test_output: ${{ steps.step_1.outputs.test_output }}
    steps:
      - name: step_1
        id: step_1
        run: |
          echo "::set-output name=test_output::blahblah"
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: step_1
        id: step_1
        run: |
          echo ${{ needs.job_1.outputs.test_output }}
    
