name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "grep matching pattern"
        run: |
         set -eo pipefail
         set +x
         echo ${GITHUB_REF}
