name: Test

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: wael-sadek/test-1
