name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST: ${{ secrets.TEST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set 
        run: TEST123=blahblah; export TEST123; echo $TEST123
      - name: test
        run: echo $TEST123
