name: Test

on: workflow_dispatch

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: step_1
        run: |
          echo 1
          IS_FORKED=$(curl -s -H "Accept: application/vnd.github+json" -H 'Authorization: Bearer ${{ github.token }}' -H "X-GitHub-Api-Version: 2022-11-28" ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY} | jq .fork)
          if [ $IS_FORKED = "false" ]
          then 
            exit 0
          fi
      - name: step_2
        run: |
          echo github.event.number = ${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.event.issue.number = ${{ github.event.issue.number }}

