name: Test

on: pull_request

jobs:
  job_1:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: step_1
        run:  gh pr merge --auto --delete-branch --squash ${GITHUB_HEAD_REF}
